{
    "name": "Liana Connector",
    "version": "19.0.1.2.0",
    "category": "Marketing",
    "author": "Liana Technologies",
    "license": "Other proprietary",
    "website": "https://www.lianatech.com/",
    "depends": [
        "base_automation",
        "crm",
        "sale",
    ],
    "data": [
        "security/liana_groups.xml",
        "security/ir.model.access.csv",
        "data/ir_sequence_data.xml",
        "data/ir_cron_data.xml",
        "views/ir_actions_server_views.xml",
        "views/liana_backend_views.xml",
        "views/liana_event_views.xml",
        "views/liana_automation_views.xml",
        "views/liana_dashboard_views.xml",
        "views/crm_lead_views.xml",
        "views/res_partner_views.xml",
        "views/liana_mailer_event_views.xml",
        "views/liana_mailing_list_views.xml",
        "wizard/liana_mailing_list_add_views.xml",
        "views/menus.xml",
        "data/default_automations.xml",
    ],
    "images": [
        "static/description/banner.png",
    ],
    "application": True,
    "installable": True,
    "auto_install": False  # Don't install when all dependencies are satisfied
}
